apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
  name: wordpress
spec:
  instanceRef:
    name: wp-db
  host: "%"
  password:
    valueFrom:
      secretKeyRef:
        name: wordpress-cloudsql-db-credentials
        key: password
