apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
  name: sql-wp-sa
spec:
  displayName: Service Account for WP access
