# TODO replace to use IAMPolicyMember
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
  name: sql-wp-sa-wi-policy
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: sql-wp-sa
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:[PROJECT_ID].svc.id.goog[default/sql-wp-ksa-wi]
        - serviceAccount:[PROJECT_ID].svc.id.goog[krns/sql-wp-ksa-wi]
        - serviceAccount:[PROJECT_ID].svc.id.goog[leaseokns/sql-wp-ksa-wi]
