apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
  labels:
    label-one: "value-one"
  name: wordpress
  namespace: krns
spec:
  charset: utf8
  instanceRef:
    name: wp-db
    namespace: default
