apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: kr-app-backend
  namespace: [SITE_NS]
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
  - port: 80
    targetPort: 80
